Fix ExceptionMessageFormat Typo (#523)
The current format of ExceptionMessageFormat causes an error on line 45: 

 System.FormatException: 'Input string was not in a correct format.'

Changes fix issue.